// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cars.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	zero "gopkg.in/guregu/null.v4/zero"
)

const checkCarOwnership = `-- name: CheckCarOwnership :one
SELECT EXISTS (
    SELECT 1 FROM cars 
    WHERE id = $1 AND owner_id = $2
) AS is_owner
`

type CheckCarOwnershipParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) CheckCarOwnership(ctx context.Context, arg CheckCarOwnershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkCarOwnership, arg.ID, arg.OwnerID)
	var is_owner bool
	err := row.Scan(&is_owner)
	return is_owner, err
}

const createCar = `-- name: CreateCar :one
INSERT INTO cars (
    "type",
    "make",
    "model",
    "year",
    "color",
    "mileage",
    "price",
    "description",
    "owner_id",
    "location"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING 
    id, type, make, model, year, color, mileage, price, description, available, 
    owner_id, location, reviews_count, created_at, updated_at
`

type CreateCarParams struct {
	Type        zero.String    `json:"type"`
	Make        zero.String    `json:"make"`
	Model       zero.String    `json:"model"`
	Year        pgtype.Int4    `json:"year"`
	Color       zero.String    `json:"color"`
	Mileage     pgtype.Int4    `json:"mileage"`
	Price       pgtype.Numeric `json:"price"`
	Description zero.String    `json:"description"`
	OwnerID     pgtype.UUID    `json:"owner_id"`
	Location    zero.String    `json:"location"`
}

type CreateCarRow struct {
	ID           string             `json:"id"`
	Type         string             `json:"type"`
	Make         string             `json:"make"`
	Model        string             `json:"model"`
	Year         int32              `json:"year"`
	Color        string             `json:"color"`
	Mileage      int32              `json:"mileage"`
	Price        interface{}        `json:"price"`
	Description  zero.String        `json:"description"`
	Available    pgtype.Bool        `json:"available"`
	OwnerID      string             `json:"owner_id"`
	Location     string             `json:"location"`
	ReviewsCount pgtype.Int4        `json:"reviews_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCar(ctx context.Context, arg CreateCarParams) (CreateCarRow, error) {
	row := q.db.QueryRow(ctx, createCar,
		arg.Type,
		arg.Make,
		arg.Model,
		arg.Year,
		arg.Color,
		arg.Mileage,
		arg.Price,
		arg.Description,
		arg.OwnerID,
		arg.Location,
	)
	var i CreateCarRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Color,
		&i.Mileage,
		&i.Price,
		&i.Description,
		&i.Available,
		&i.OwnerID,
		&i.Location,
		&i.ReviewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCar = `-- name: DeleteCar :exec
DELETE FROM cars WHERE id = $1
`

func (q *Queries) DeleteCar(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCar, id)
	return err
}

const getCarById = `-- name: GetCarById :one
SELECT 
    c.id, c.type, c.make, c.model, c.year, c.color, c.mileage, c.price, 
    c.description, c.available, c.owner_id, c.location, c.reviews_count, 
    c.created_at, c.updated_at,
    COALESCE(
        json_agg(
            jsonb_build_object(
                'id', i.id,
                'car_id', i.car_id,
                'filename', i.filename,
                'uploaded_at', i.uploaded_at
            )
        ) FILTER (WHERE i.deleted_at = 0), '[]'
    ) AS images
FROM cars c
LEFT JOIN images i ON c.id = i.car_id
WHERE c.id = $1
GROUP BY c.id
`

type GetCarByIdRow struct {
	ID           string             `json:"id"`
	Type         string             `json:"type"`
	Make         string             `json:"make"`
	Model        string             `json:"model"`
	Year         int32              `json:"year"`
	Color        string             `json:"color"`
	Mileage      int32              `json:"mileage"`
	Price        interface{}        `json:"price"`
	Description  zero.String        `json:"description"`
	Available    pgtype.Bool        `json:"available"`
	OwnerID      string             `json:"owner_id"`
	Location     string             `json:"location"`
	ReviewsCount pgtype.Int4        `json:"reviews_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Images       []byte             `json:"images"`
}

func (q *Queries) GetCarById(ctx context.Context, id pgtype.UUID) (GetCarByIdRow, error) {
	row := q.db.QueryRow(ctx, getCarById, id)
	var i GetCarByIdRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Color,
		&i.Mileage,
		&i.Price,
		&i.Description,
		&i.Available,
		&i.OwnerID,
		&i.Location,
		&i.ReviewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Images,
	)
	return i, err
}

const incrementCarReviewCount = `-- name: IncrementCarReviewCount :exec
UPDATE cars
SET reviews_count = reviews_count + 1
WHERE id = $1
`

func (q *Queries) IncrementCarReviewCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementCarReviewCount, id)
	return err
}

const listCars = `-- name: ListCars :many
SELECT 
    c.id, c.type, c.make, c.model, c.year, c.color, c.mileage, c.price, 
    c.description, c.available, c.owner_id, c.location, c.reviews_count, 
    c.created_at, c.updated_at,
    COALESCE(
        json_agg(
            jsonb_build_object(
                'id', i.id,
                'car_id', i.car_id,
                'filename', i.filename,
                'uploaded_at', i.uploaded_at
            )
        ) FILTER (WHERE i.deleted_at = 0), '[]'
    ) AS images
FROM cars c
LEFT JOIN images i ON c.id = i.car_id
WHERE 
    ($1::TEXT IS NULL OR c.type = $1::TEXT)
    AND ($2::TEXT IS NULL OR c.location = $2::TEXT)
    -- Add price range filters
    AND ($3::DECIMAL(10,2) IS NULL OR c.price >= $3::DECIMAL(10,2))
    AND ($4::DECIMAL(10,2) IS NULL OR c.price <= $4::DECIMAL(10,2))
    AND ($5::UUID IS NULL OR c.owner_id = $5::UUID)
GROUP BY 
    c.id, c.type, c.make, c.model, c.year, c.color, c.mileage, c.price, 
    c.description, c.available, c.owner_id, c.location, c.reviews_count, 
    c.created_at, c.updated_at
ORDER BY 
    CASE 
        WHEN $6::TEXT = 'asc' THEN c.price 
    END ASC,
    CASE 
        WHEN $6::TEXT = 'desc' THEN c.price 
    END DESC,
    c.created_at DESC
LIMIT $8::INTEGER OFFSET $7::INTEGER
`

type ListCarsParams struct {
	Type       zero.String    `json:"type"`
	Location   zero.String    `json:"location"`
	MinPrice   pgtype.Numeric `json:"min_price"`
	MaxPrice   pgtype.Numeric `json:"max_price"`
	UserID     pgtype.UUID    `json:"user_id"`
	PriceOrder zero.String    `json:"price_order"`
	Offset     pgtype.Int4    `json:"offset"`
	Limit      pgtype.Int4    `json:"limit"`
}

type ListCarsRow struct {
	ID           string             `json:"id"`
	Type         string             `json:"type"`
	Make         string             `json:"make"`
	Model        string             `json:"model"`
	Year         int32              `json:"year"`
	Color        string             `json:"color"`
	Mileage      int32              `json:"mileage"`
	Price        interface{}        `json:"price"`
	Description  zero.String        `json:"description"`
	Available    pgtype.Bool        `json:"available"`
	OwnerID      string             `json:"owner_id"`
	Location     string             `json:"location"`
	ReviewsCount pgtype.Int4        `json:"reviews_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Images       []byte             `json:"images"`
}

func (q *Queries) ListCars(ctx context.Context, arg ListCarsParams) ([]ListCarsRow, error) {
	rows, err := q.db.Query(ctx, listCars,
		arg.Type,
		arg.Location,
		arg.MinPrice,
		arg.MaxPrice,
		arg.UserID,
		arg.PriceOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCarsRow
	for rows.Next() {
		var i ListCarsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Make,
			&i.Model,
			&i.Year,
			&i.Color,
			&i.Mileage,
			&i.Price,
			&i.Description,
			&i.Available,
			&i.OwnerID,
			&i.Location,
			&i.ReviewsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Images,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCar = `-- name: SearchCar :many
SELECT 
    c.id, c.type, c.make, c.model, c.year, c.color, c.mileage, c.price, 
    c.description, c.available, c.owner_id, c.location, c.reviews_count, 
    c.created_at, c.updated_at,
    COALESCE(
        json_agg(
            jsonb_build_object(
                'id', i.id,
                'car_id', i.car_id,
                'filename', i.filename,
                'uploaded_at', i.uploaded_at
            )
        ) FILTER (WHERE i.deleted_at = 0), '[]'
    ) AS images
FROM cars c
LEFT JOIN images i ON c.id = i.car_id
WHERE 
    COALESCE($1, '') = '' OR 
    c.make ILIKE '%' || $1 || '%' OR 
    c.model ILIKE '%' || $1 || '%'
GROUP BY 
    c.id, c.type, c.make, c.model, c.year, c.color, c.mileage, c.price, 
    c.description, c.available, c.owner_id, c.location, c.reviews_count, 
    c.created_at, c.updated_at
ORDER BY c.created_at DESC
LIMIT $3 OFFSET $2
`

type SearchCarParams struct {
	Query  zero.String `json:"query"`
	Offset pgtype.Int8 `json:"offset"`
	Limit  pgtype.Int8 `json:"limit"`
}

type SearchCarRow struct {
	ID           string             `json:"id"`
	Type         string             `json:"type"`
	Make         string             `json:"make"`
	Model        string             `json:"model"`
	Year         int32              `json:"year"`
	Color        string             `json:"color"`
	Mileage      int32              `json:"mileage"`
	Price        interface{}        `json:"price"`
	Description  zero.String        `json:"description"`
	Available    pgtype.Bool        `json:"available"`
	OwnerID      string             `json:"owner_id"`
	Location     string             `json:"location"`
	ReviewsCount pgtype.Int4        `json:"reviews_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Images       []byte             `json:"images"`
}

func (q *Queries) SearchCar(ctx context.Context, arg SearchCarParams) ([]SearchCarRow, error) {
	rows, err := q.db.Query(ctx, searchCar, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCarRow
	for rows.Next() {
		var i SearchCarRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Make,
			&i.Model,
			&i.Year,
			&i.Color,
			&i.Mileage,
			&i.Price,
			&i.Description,
			&i.Available,
			&i.OwnerID,
			&i.Location,
			&i.ReviewsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Images,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCar = `-- name: UpdateCar :exec
UPDATE cars
SET type = $1, make = $2, model = $3, year = $4, 
    color = $5, mileage = $6, price = $7,
    description = $8, available = $9, location = $10, 
    updated_at = CURRENT_TIMESTAMP
WHERE id = $11
`

type UpdateCarParams struct {
	Type        zero.String    `json:"type"`
	Make        zero.String    `json:"make"`
	Model       zero.String    `json:"model"`
	Year        pgtype.Int4    `json:"year"`
	Color       zero.String    `json:"color"`
	Mileage     pgtype.Int4    `json:"mileage"`
	Price       pgtype.Numeric `json:"price"`
	Description zero.String    `json:"description"`
	Available   pgtype.Bool    `json:"available"`
	Location    zero.String    `json:"location"`
	ID          pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateCar(ctx context.Context, arg UpdateCarParams) error {
	_, err := q.db.Exec(ctx, updateCar,
		arg.Type,
		arg.Make,
		arg.Model,
		arg.Year,
		arg.Color,
		arg.Mileage,
		arg.Price,
		arg.Description,
		arg.Available,
		arg.Location,
		arg.ID,
	)
	return err
}
