// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: comments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	zero "gopkg.in/guregu/null.v4/zero"
)

const checkCommentOwnership = `-- name: CheckCommentOwnership :one
SELECT EXISTS (
    SELECT 1 FROM comments 
    WHERE id = $1 AND user_id = $2
) AS is_owner
`

type CheckCommentOwnershipParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CheckCommentOwnership(ctx context.Context, arg CheckCommentOwnershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkCommentOwnership, arg.ID, arg.UserID)
	var is_owner bool
	err := row.Scan(&is_owner)
	return is_owner, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
    "user_id",
    "car_id",
    "content"
) VALUES (
    $1,
    $2,
    $3
)
RETURNING 
    id, user_id, car_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	CarID   pgtype.UUID `json:"car_id"`
	Content zero.String `json:"content"`
}

type CreateCommentRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	CarID     string             `json:"car_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment, arg.UserID, arg.CarID, arg.Content)
	var i CreateCommentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CarID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments 
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const deleteCommentsByCarId = `-- name: DeleteCommentsByCarId :exec
DELETE FROM comments 
WHERE car_id = $1
`

func (q *Queries) DeleteCommentsByCarId(ctx context.Context, carID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCommentsByCarId, carID)
	return err
}

const getCommentsByCar = `-- name: GetCommentsByCar :many
SELECT 
    id, user_id, car_id, content, created_at, updated_at
FROM comments
WHERE car_id = $1 AND deleted_at = 0
`

type GetCommentsByCarRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	CarID     string             `json:"car_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCommentsByCar(ctx context.Context, carID pgtype.UUID) ([]GetCommentsByCarRow, error) {
	rows, err := q.db.Query(ctx, getCommentsByCar, carID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByCarRow
	for rows.Next() {
		var i GetCommentsByCarRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CarID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :exec
UPDATE comments
SET 
    content = $1, 
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateCommentParams struct {
	Content zero.String `json:"content"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.db.Exec(ctx, updateComment, arg.Content, arg.ID)
	return err
}
