// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: images.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	zero "gopkg.in/guregu/null.v4/zero"
)

const addImage = `-- name: AddImage :one
INSERT INTO images (car_id, filename)
VALUES ($1, $2)
RETURNING id, car_id, filename, uploaded_at
`

type AddImageParams struct {
	CarID    pgtype.UUID `json:"car_id"`
	Filename zero.String `json:"filename"`
}

type AddImageRow struct {
	ID         string             `json:"id"`
	CarID      string             `json:"car_id"`
	Filename   string             `json:"filename"`
	UploadedAt pgtype.Timestamptz `json:"uploaded_at"`
}

func (q *Queries) AddImage(ctx context.Context, arg AddImageParams) (AddImageRow, error) {
	row := q.db.QueryRow(ctx, addImage, arg.CarID, arg.Filename)
	var i AddImageRow
	err := row.Scan(
		&i.ID,
		&i.CarID,
		&i.Filename,
		&i.UploadedAt,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteImage, id)
	return err
}

const deleteImagesByCarId = `-- name: DeleteImagesByCarId :exec
DELETE FROM images WHERE car_id = $1
`

func (q *Queries) DeleteImagesByCarId(ctx context.Context, carID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteImagesByCarId, carID)
	return err
}

const getImageById = `-- name: GetImageById :one
SELECT id, car_id, filename, uploaded_at
FROM images
WHERE id = $1
`

type GetImageByIdRow struct {
	ID         string             `json:"id"`
	CarID      string             `json:"car_id"`
	Filename   string             `json:"filename"`
	UploadedAt pgtype.Timestamptz `json:"uploaded_at"`
}

func (q *Queries) GetImageById(ctx context.Context, id pgtype.UUID) (GetImageByIdRow, error) {
	row := q.db.QueryRow(ctx, getImageById, id)
	var i GetImageByIdRow
	err := row.Scan(
		&i.ID,
		&i.CarID,
		&i.Filename,
		&i.UploadedAt,
	)
	return i, err
}

const getImagesByCar = `-- name: GetImagesByCar :many
SELECT id, car_id, filename, uploaded_at
FROM images
WHERE car_id = $1
`

type GetImagesByCarRow struct {
	ID         string             `json:"id"`
	CarID      string             `json:"car_id"`
	Filename   string             `json:"filename"`
	UploadedAt pgtype.Timestamptz `json:"uploaded_at"`
}

func (q *Queries) GetImagesByCar(ctx context.Context, carID pgtype.UUID) ([]GetImagesByCarRow, error) {
	rows, err := q.db.Query(ctx, getImagesByCar, carID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetImagesByCarRow
	for rows.Next() {
		var i GetImagesByCarRow
		if err := rows.Scan(
			&i.ID,
			&i.CarID,
			&i.Filename,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
