// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	zero "gopkg.in/guregu/null.v4/zero"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, message)
VALUES ($1, $2, $3)
RETURNING id, user_id, type, message, seen, created_at
`

type CreateNotificationParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Type    zero.String `json:"type"`
	Message zero.String `json:"message"`
}

type CreateNotificationRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Type      string             `json:"type"`
	Message   string             `json:"message"`
	Seen      pgtype.Bool        `json:"seen"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.UserID, arg.Type, arg.Message)
	var i CreateNotificationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Message,
		&i.Seen,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications WHERE id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotification, id)
	return err
}

const getNotificationsByUser = `-- name: GetNotificationsByUser :many
SELECT id, user_id, type, message, seen, created_at
FROM notifications
WHERE user_id = $1 AND deleted_at = 0
`

type GetNotificationsByUserRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Type      string             `json:"type"`
	Message   string             `json:"message"`
	Seen      pgtype.Bool        `json:"seen"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetNotificationsByUser(ctx context.Context, userID pgtype.UUID) ([]GetNotificationsByUserRow, error) {
	rows, err := q.db.Query(ctx, getNotificationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationsByUserRow
	for rows.Next() {
		var i GetNotificationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Message,
			&i.Seen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationsByUser = `-- name: GetUnreadNotificationsByUser :many
SELECT id, user_id, type, message, seen, created_at
FROM notifications
WHERE user_id = $1 AND seen = false AND deleted_at = 0
`

type GetUnreadNotificationsByUserRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Type      string             `json:"type"`
	Message   string             `json:"message"`
	Seen      pgtype.Bool        `json:"seen"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUnreadNotificationsByUser(ctx context.Context, userID pgtype.UUID) ([]GetUnreadNotificationsByUserRow, error) {
	rows, err := q.db.Query(ctx, getUnreadNotificationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnreadNotificationsByUserRow
	for rows.Next() {
		var i GetUnreadNotificationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Message,
			&i.Seen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications 
SET seen = true, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkNotificationAsRead(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationAsRead, id)
	return err
}
