// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notifications_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	zero "gopkg.in/guregu/null.v4/zero"
)

const createNotificationToken = `-- name: CreateNotificationToken :one
INSERT INTO notifications_tokens (user_id, token, platform)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, platform, created_at, updated_at
`

type CreateNotificationTokenParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Token    zero.String `json:"token"`
	Platform zero.String `json:"platform"`
}

type CreateNotificationTokenRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Token     string             `json:"token"`
	Platform  string             `json:"platform"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateNotificationToken(ctx context.Context, arg CreateNotificationTokenParams) (CreateNotificationTokenRow, error) {
	row := q.db.QueryRow(ctx, createNotificationToken, arg.UserID, arg.Token, arg.Platform)
	var i CreateNotificationTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotificationToken = `-- name: DeleteNotificationToken :exec
DELETE FROM notifications_tokens WHERE id = $1
`

func (q *Queries) DeleteNotificationToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotificationToken, id)
	return err
}

const deleteNotificationTokensByUserId = `-- name: DeleteNotificationTokensByUserId :exec
DELETE FROM notifications_tokens WHERE user_id = $1
`

func (q *Queries) DeleteNotificationTokensByUserId(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotificationTokensByUserId, userID)
	return err
}

const getNotificationTokensByUserId = `-- name: GetNotificationTokensByUserId :many
SELECT id, user_id, token, platform, created_at, updated_at
FROM notifications_tokens
WHERE user_id = $1
`

type GetNotificationTokensByUserIdRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Token     string             `json:"token"`
	Platform  string             `json:"platform"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetNotificationTokensByUserId(ctx context.Context, userID pgtype.UUID) ([]GetNotificationTokensByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getNotificationTokensByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationTokensByUserIdRow
	for rows.Next() {
		var i GetNotificationTokensByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationToken = `-- name: UpdateNotificationToken :exec
UPDATE notifications_tokens
SET token = $1, platform = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3
`

type UpdateNotificationTokenParams struct {
	Token    zero.String `json:"token"`
	Platform zero.String `json:"platform"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateNotificationToken(ctx context.Context, arg UpdateNotificationTokenParams) error {
	_, err := q.db.Exec(ctx, updateNotificationToken, arg.Token, arg.Platform, arg.ID)
	return err
}
