// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddImage(ctx context.Context, arg AddImageParams) (AddImageRow, error)
	CheckCarOwnership(ctx context.Context, arg CheckCarOwnershipParams) (bool, error)
	CheckCommentOwnership(ctx context.Context, arg CheckCommentOwnershipParams) (bool, error)
	CheckMessageOwnership(ctx context.Context, arg CheckMessageOwnershipParams) (bool, error)
	CheckSavedCarOwnership(ctx context.Context, arg CheckSavedCarOwnershipParams) (bool, error)
	CreateCar(ctx context.Context, arg CreateCarParams) (CreateCarRow, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error)
	CreateNotificationToken(ctx context.Context, arg CreateNotificationTokenParams) (CreateNotificationTokenRow, error)
	CreateSavedCar(ctx context.Context, arg CreateSavedCarParams) (CreateSavedCarRow, error)
	DeleteCar(ctx context.Context, id pgtype.UUID) error
	DeleteComment(ctx context.Context, id pgtype.UUID) error
	DeleteCommentsByCarId(ctx context.Context, carID pgtype.UUID) error
	DeleteImage(ctx context.Context, id pgtype.UUID) error
	DeleteImagesByCarId(ctx context.Context, carID pgtype.UUID) error
	DeleteMessage(ctx context.Context, id pgtype.UUID) error
	DeleteNotification(ctx context.Context, id pgtype.UUID) error
	DeleteNotificationToken(ctx context.Context, id pgtype.UUID) error
	DeleteNotificationTokensByUserId(ctx context.Context, userID pgtype.UUID) error
	DeleteSavedCar(ctx context.Context, id pgtype.UUID) error
	DeleteSavedCarsByCarId(ctx context.Context, carID pgtype.UUID) error
	GetCarById(ctx context.Context, id pgtype.UUID) (GetCarByIdRow, error)
	GetCommentsByCar(ctx context.Context, carID pgtype.UUID) ([]GetCommentsByCarRow, error)
	GetImageById(ctx context.Context, id pgtype.UUID) (GetImageByIdRow, error)
	GetImagesByCar(ctx context.Context, carID pgtype.UUID) ([]GetImagesByCarRow, error)
	GetMessagesByUser(ctx context.Context, userID pgtype.UUID) ([]GetMessagesByUserRow, error)
	GetMessagesByUserAndId(ctx context.Context, arg GetMessagesByUserAndIdParams) ([]GetMessagesByUserAndIdRow, error)
	GetNotificationTokensByUserId(ctx context.Context, userID pgtype.UUID) ([]GetNotificationTokensByUserIdRow, error)
	GetNotificationsByUser(ctx context.Context, userID pgtype.UUID) ([]GetNotificationsByUserRow, error)
	GetSavedCarsByUser(ctx context.Context, userID pgtype.UUID) ([]GetSavedCarsByUserRow, error)
	GetUnreadNotificationsByUser(ctx context.Context, userID pgtype.UUID) ([]GetUnreadNotificationsByUserRow, error)
	IncrementCarReviewCount(ctx context.Context, id pgtype.UUID) error
	ListCars(ctx context.Context, arg ListCarsParams) ([]ListCarsRow, error)
	MarkMessageAsRead(ctx context.Context, id pgtype.UUID) error
	MarkNotificationAsRead(ctx context.Context, id pgtype.UUID) error
	SearchCar(ctx context.Context, arg SearchCarParams) ([]SearchCarRow, error)
	UpdateCar(ctx context.Context, arg UpdateCarParams) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) error
	UpdateNotificationToken(ctx context.Context, arg UpdateNotificationTokenParams) error
}

var _ Querier = (*Queries)(nil)
