// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: saved_cars.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkSavedCarOwnership = `-- name: CheckSavedCarOwnership :one
SELECT EXISTS (
    SELECT 1 FROM saved_cars
    WHERE id = $1 AND user_id = $2
) AS is_owner
`

type CheckSavedCarOwnershipParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CheckSavedCarOwnership(ctx context.Context, arg CheckSavedCarOwnershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSavedCarOwnership, arg.ID, arg.UserID)
	var is_owner bool
	err := row.Scan(&is_owner)
	return is_owner, err
}

const createSavedCar = `-- name: CreateSavedCar :one
INSERT INTO saved_cars (user_id, car_id)
VALUES (
    $1,
    $2
)
RETURNING id, user_id, car_id, created_at, updated_at
`

type CreateSavedCarParams struct {
	UserID pgtype.UUID `json:"user_id"`
	CarID  pgtype.UUID `json:"car_id"`
}

type CreateSavedCarRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	CarID     string             `json:"car_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSavedCar(ctx context.Context, arg CreateSavedCarParams) (CreateSavedCarRow, error) {
	row := q.db.QueryRow(ctx, createSavedCar, arg.UserID, arg.CarID)
	var i CreateSavedCarRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CarID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSavedCar = `-- name: DeleteSavedCar :exec
DELETE FROM saved_cars WHERE id = $1
`

func (q *Queries) DeleteSavedCar(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSavedCar, id)
	return err
}

const deleteSavedCarsByCarId = `-- name: DeleteSavedCarsByCarId :exec
DELETE FROM saved_cars WHERE car_id = $1
`

func (q *Queries) DeleteSavedCarsByCarId(ctx context.Context, carID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSavedCarsByCarId, carID)
	return err
}

const getSavedCarsByUser = `-- name: GetSavedCarsByUser :many
SELECT id, user_id, car_id, created_at, updated_at
FROM saved_cars
WHERE user_id = $1
`

type GetSavedCarsByUserRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	CarID     string             `json:"car_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSavedCarsByUser(ctx context.Context, userID pgtype.UUID) ([]GetSavedCarsByUserRow, error) {
	rows, err := q.db.Query(ctx, getSavedCarsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSavedCarsByUserRow
	for rows.Next() {
		var i GetSavedCarsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CarID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
